## Common model & probability settings for all experiments

# Directories and file patterns
dataset_dir: [data, processed]
results_dir: [results, base]
scenarios_dir: [scenarios, base]

# Available years of data
wind_years: &wind_years [2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
solar_years: &solar_years [2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]
price_years: [2023,2024]
carbon_years: [2023,2024]

# Location of assets
site_location: [51.95,4.1]
wind_location: [52.7,3.5]

# Default energy model settings
model_settings:
  T: 8760
  initial_SoC: 0.75 # must be > 1 - min(DoD)
  grid_capacity: 500.0e+3 # kW
  capex_budget: 2.0e+8 # €/yr (4e9/20)
  solar_capacity_limit: 500.0e+3 # kWp
  N_technologies: 1
  storage_technologies: [Li-ion]
  allow_elec_purchase: True
  use_CVaR: False

# Default solver settings
solver_settings:
  solver_name: highs # highs, cupdlpx

# Probabilistic model settings
probability_settings: # tuples are [mu,sigma]
  n_prior_samples: 250
  n_posterior_samples: 250
  n_reduced_scenarios: 100
  sampling_thin_factor: 10
  measurement_sigma_reduction: 0.25
  load_level: [250000,25000]
  wind_years: *wind_years
  solar_years: *solar_years
  price_year: 2023
  carbon_year: 2023
  storage:
    CAES:
      cost: [50,15]
      lifetime: [25,2.5]
      efficiency: [0.6,0.025]
    Li-ion:
      cost: [200,50]
      lifetime: [20,5]
      efficiency: [0.92,0.035]
    NaS:
      cost: [175,37.5]
      lifetime: [25,5]
      efficiency: [0.8,0.05]
    VRBF:
      cost: [250,75]
      lifetime: [20,5]
      efficiency: [0.75,0.05]
    # Pb-acid:
    #   cost: [150,50]
    #   lifetime: [12.5,3.75]
    #   efficiency: [0.725,0.0375]
    # PCM:
    #   cost: [40,15]
    #   lifetime: [30,5]
    #   efficiency: [0.65,0.125]